# Generated by Django 5.1.6 on 2025-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('servicos', 'Serviços'), ('produtos', 'Produtos'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
