# Generated by Django 5.1.6 on 2025-05-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financas', '0002_receita_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('custos fixos', 'custos fixos'), ('produtos', 'produtos'), ('salario', 'salario'), ('outros', 'outros')], default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('cortes', 'Cortes'), ('tratamento', 'Tratamento'), ('finalizacao', 'Finalização'), ('quimica', 'Química'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
