# Generated by Django 5.1.6 on 2025-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('entrada_no_estoque', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('custo_aquisicao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
