# Generated by Django 5.1.6 on 2025-04-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('entrada_no_estoque', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_estoque.estoque')),
            ],
        ),
    ]
