# Generated by Django 5.1.6 on 2025-05-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0001_initial'),
        ('app_perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('preco_aquisicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_estoque', to='app_perfil.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='Item_Estoque',
        ),
    ]
