# Generated by Django 5.1.6 on 2025-04-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_estoque',
            name='estoque',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
