# Generated by Django 5.1.6 on 2025-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0002_remove_item_estoque_estoque_delete_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_estoque',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
