# Generated by Django 5.1.6 on 2025-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0003_item_estoque_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_estoque',
            name='custo_aquisicao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
