# Generated by Django 5.1.6 on 2025-05-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Pendente'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='agendado', max_length=10),
        ),
    ]
